### ISSUE TITLE
Question: Is there a way to minimize support, assuming support is only generated "from buildplate/bed"?

### ISSUE THREAD

**Issue by jerryfromearth** [ChristophSchranz/Tweaker-3#12]
Hello! Thanks for the project!

There's a model (https://cdn.thingiverse.com/assets/70/96/59/c1/62/RIGHT_Q1_single_piece_SolidSlime_1.3.stl), where I ONLY want support to be generated from buildplate, otherwise support will leave some scarred interface on some surface. 
But I can only make tweaker-3 (actually, the cura wrapper plugin) to orient it in a way that it can only be printed when support is generated from anywhere, otherwise some dramatic overhang will fail.

How tweaker-3 orient it (the top part has some dangerous overhang):
![image](https://user-images.githubusercontent.com/343557/116052838-5065c580-a67a-11eb-80db-41fc86292cbf.png)

How I assume tweaker-3 should orient it:
![image](https://user-images.githubusercontent.com/343557/116052899-64112c00-a67a-11eb-8702-ba81484609fd.png)

So is there any way to make Tweaker-3 optimize support while assuming support is only generated from the buildplate? Thanks.

**Comment by ChristophSchranz** [comment]
Hello @jerryfromearth 
Unfortunately not. However, there will be a big update in summer that will also improve the quality of auto-rotations when support material is supported. In principle it would be possible to make an additional usage mode that is optimized for "support to buildplate ONLY". This would need some additional effort so I hope it will work with the next big release!

**Comment by jerryfromearth** [comment]
@ChristophSchranz Thank you! I'm grateful that you are still working on this after so many years. Looking forward to the big update!

**Comment by AlbertMN** [comment]
We're looking forward to the update as well! Keep up the amazing work :)
