### ISSUE TITLE
Favorite side function documentation

### ISSUE THREAD

**Issue by EvgeniGenchev** [ChristophSchranz/Tweaker-3#14]
When it comes to 3D printing object for production the strength of the object in a given orientation is important. I have been trying to generate two objects with Tweaker-3, one upstanding and one laying on one of the side. The documentation on the `-fs` function is a little bit vague. Thus, I can seem to figure out if there is a way using the favorite side function in order to achieve restrictions on certain axis rotations?

**Comment by ChristophSchranz** [comment]
Hi @EvgeniGenchev 
yes that's right, I've updated the description in 25331d6c775cfcdfcd24c4ec28f93120f23295a8.
Let me know if it is better understandable now.

Restrictions of certain orientations are btw. not intended by using the `favside`. It is nevertheless worth trying if it works for you.

**Comment by ChristophSchranz** [comment]
Closing as the documentation was improved and no further questions have been raised.
