### ISSUE TITLE
#notabug Do you have use cases pictures?

### ISSUE THREAD

**Issue by franzbischoff** [ChristophSchranz/Tweaker-3#4]
The one example in your readme doesn't show the full potential of the script. Do you have other examples to get a better notion?

Thank you

**Comment by ChristophSchranz** [comment]
I guess you mean the example in that the support material volume is minimized. Unfortunately, this extra feature was developed for an use-case in another company that didn't want to share the object, as it is from a third-party. In that case, the object needed a lot of support material anyway, so the purpose here was to minimize this extra material so save printing time, material cost and energy.

The other usages just take the file-conversion and verbose (showing all logs) into account, 

If you are interested in a more detailed description, have a look at this [blog](https://www.salzburgresearch.at/blog/3d-print-positioning/) (it describes a numpy-free version with the same function).

I hope my answer could help you!

**Comment by ChristophSchranz** [comment]
I close the issue as the question seems to be answered.
