### ISSUE TITLE
Unavailable after installation.    cura15&cura 2.7

### ISSUE THREAD

**Issue by HonestGit** [ChristophSchranz/Tweaker-3#6]

**Comment by ChristophSchranz** [comment]
Hi @HonestGit,
please tell me more about the issue:
What can the problem be reproduced and what is it exactly?

By the way, from **Cura 3** on, the **Tweaker** is found as **Auto-Orientation Module** in the **PlugIn-Manager**, where it should work as expected!

**Comment by HonestGit** [comment]
Hello Mr. Chris
I used two versions, cura15.04 and cura2.7

Tweaker-Plugin for Cura 15.04

The file printableObject.py was modified to replace Cura's "layflat" function with the Tweaker's Auto Rotate.


cura15.04
No prompt after installation.Can't rotate automatically after clicking layflat

Cura Plugin:Cura 15 and Cura 2.3 are supported. Installation infos are in the PlugIn folder, or you can also download the PlugIn from Cura 2.7 PlugIn Browser.

cura2.7&nbsp;

No prompt after installation, no information about it in the plugin browser


I want to know what version of cura you are using and how to use it.

I would appreciate it if you could attach installation videos and use videos





 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chris"<notifications@github.com&gt;; 
发送时间: 2020年1月11日(星期六) 晚上6:51
收件人: "ChristophSchranz/Tweaker-3"<Tweaker-3@noreply.github.com&gt;; 
抄送: "某猫"<547389457@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ChristophSchranz/Tweaker-3] Unavailable after installation.    cura15&amp;cura 2.7 (#6)




Hi @HonestGit,
 please tell me more about the issue:
 What can the problem be reproduced and what is it exactly?
 
By the way, from Cura 3 on, the Tweaker is found as Auto-Orientation Module in the PlugIn-Manager, where it should work as expected!

**Comment by ChristophSchranz** [comment]
Dear @HonestGit,
Cura 15.0X and Cura 2.X were state of the art when I developed this software and I therefore provided some plugins before it became an third-party plugin available within the Cura UI.

However, I would suggest to use a newer version of Cura, as version 3 and 4 are much faster and really great. In both versions you can install this *Tweaker-3* with the name **Auto-Orientation**. See this video on how to install a Plugin in Cura 4.
[![Click here](http://i3.ytimg.com/vi/sIsu-GiURuw/hqdefault.jpg)](https://www.youtube.com/watch?v=sIsu-GiURuw)

I hope this helps you!

**Comment by ChristophSchranz** [comment]
I suppose my answer helped you, therefore I close this issue.
