### ISSUE TITLE
SyntaxError: invalid syntax w/ demo.stl

### ISSUE THREAD

**Issue by shaiss** [ChristophSchranz/Tweaker-3#7]
I cloned the repo and ran the first command in the readme and get the below syntax error.  Am I possibly missing some dependancy?

```
a483e711095a:Tweaker-3 speredni$ python Tweaker.py -i demo_object.stl -vb
Traceback (most recent call last):
  File "Tweaker.py", line 8, in <module>
    from MeshTweaker import Tweak
  File "/Users/speredni/Documents/Tweaker-3/MeshTweaker.py", line 451
    print("\nProgress is: {}".format(progress), end="")
                                                   ^
SyntaxError: invalid syntax
```

Python version info:
```
Python 2.7.16 (default, Dec  3 2019, 07:02:07) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
```

**Comment by ChristophSchranz** [comment]
Thanks for adding the version info!

`print` is not a function in python 2. Have you tried python 3 too?

As this line is only executed in the verbose mode using the `-vb` parameter, you may be save by just not using this mode ;) 

If you want to use python 2, [here](https://stackoverflow.com/questions/2456148/python-print-end) is a discussion about exactly that.
